CostParser: blastparser.o doubleparser.o

blastparser.o: blastparser.h blastparser.cpp
	g++ -c -O2 -I. blastparser.cpp

doubleparser.o: doubleparser.h doubleparser.cpp
	g++ -c -O2 -I. doubleparser.cpp

